PROGRAM AS
IMPLICIT NONE
INTEGER GSAYI, I
PRINT*,"BIR SAYI GIRIN: "
READ*, GSAYI

DO I = 2,GSAYI-1
    IF(MOD(GSAYI,I) == 0)THEN
        PRINT*,"ASAL SAYI DEGIL"
        EXIT
    ELSE
        PRINT*,"ASAL SAYI"
        EXIT
    END IF    
END DO
END PROGRAM AS